### ISSUE TITLE
good bots vs bad bots

### ISSUE THREAD

**Issue by Daijobou** [fabiomb/is_bot#8]
Currently, the list of bots does not distinguish between good and bad bots. Some of the bots can also be locked out via "robots.txt". Also missing is the URL to the bot to get information about it.

**Comment by fabiomb** [comment]
it was not the intention of the function, if you need a blacklist is different and a malicious bot usually does not recognices it is in the user agent, they fill the user agent with false information. One way to detect it is reading the version (eg: an old Chrome or Firefox) but is not efficient. Here i'm only collecting "openly recognized bots", not bad ones. And of course you can lock them via robots.txt but not every time you need to block, in my case i detect them just for understand what they do.
